
GET http://localhost:3000/predator

###

GET http://localhost:3000/mercurial

###

GET http://localhost:3000/puma

###

GET http://localhost:3000/all
 
###

GET http://localhost:3000/query_param?id=1
