GET http://localhost:3000/products.json

###

GET http://localhost:3000/products/9.json

###

POST http://localhost:3000/products.json
content-type: application/json

{
  "name" : "New Balance Furon v6+ Pro Wide FG Soccer Cleat",
  "price" : 199.99,
  "description" : "The Furon V6+ is re-engineered with the next generation of Fit Weave technology from New Balance in the Hypoknit upper. This provides a sock-like fit with great stability and a low profile knitted collar for a freedom of movement on the ball. A Hyposkin clear film is on top of the Hypoknit upper to prevent water uptake on those rainy and damp days.",
  "supplier_id" : 5
}

###

PATCH http://localhost:3000/products/21.json
content-type: application/json

{
  "name": "New Balance Furon V6+ Pro FG Soccer Cleat: Sadio Mane The Lion Roars",
  "price": 224.99,
  "description": "Pure Instinct. Sadio Mane's new signature New Balance Furon 6+ cleats - The Lion Roars - are made for explosive power and skill that the Liverpool and Senegal star embodies, and feature eye-catching bespoke graphics. New Balance's next generation Fit Weave technology provides a sock-like fit with great stability and a low profile knitted collar for a freedom of movement on the ball. A Hyposkin clear film is on top of the Hypoknit upper to prevent water uptake on those rainy and damp days.",
  "supplier_id": 5
}

### 

DELETE http://localhost:3000/products/9

###
GET http://localhost:3000/suppliers.json

###
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Jurgen Klopp",
  "email": "JKlopp@LFC.com",
  "password": "YNWA",
  "password_confirmation": "YNWA"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "JKlopp@LFC.com",
  "password": "YNWA"
}

### Orders create
POST http://localhost:3000/orders.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDgwNTY2NDV9.vM5pHmwElmC4hSli0RZWHsltKAWK0vUsvTXNY-DESiQ
Content-Type: application/json

{
  "product_id" : 7,
  "quantity" : 3
}

### Orders show
GET http://localhost:3000/orders/3


### Orders index (show all)
GET http://localhost:3000/orders.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDgwNTY2NDV9.vM5pHmwElmC4hSli0RZWHsltKAWK0vUsvTXNY-DESiQ